### ISSUE TITLE
error install pqkmeans

### ISSUE THREAD

**Issue by HossamAmer12** [avidale/compress-fasttext#19]
When I try to install pqkmeans, I find this error:

>     
      running install_egg_info
      Copying lshash3.egg-info to build/bdist.linux-x86_64/wheel/lshash3-0.0.8-py3.8.egg-info
      running install_scripts
      error: invalid command 'bdist_wininst'
      [end of output]note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for lshash3

Any clue about lshash3?

**Comment by avidale** [comment]
No idea. 
Can you share the environment you are working with? 
OS, Python version, etc. 
I'll try reproducing the problem.

**Comment by HossamAmer12** [comment]
Thanks so much.

Just want to share the only way I found to solve this:
0. Create a conda env with python3.7
1. Clone the repo
2. pip install -r requirements.txt
3. pip install compress-fasttext==0.0.7

if needed
pip install fasttext==0.9.2

**Comment by HossamAmer12** [comment]
@avidale I am still confused as to why I cannot install the latest compress fasttext

Python3.8 - Ubunto 18.0 - compress-fasttext==0.1.3 gensim==4.3.2

Using the old compress fast text is causing me other issues

**Comment by HossamAmer12** [comment]
Made SO question for this problem:
https://stackoverflow.com/questions/77258294/compressfasttext-pqkmeans-does-not-install

**Comment by avidale** [comment]
The problem seems to be with installing `lshash3`, which is the dependency of `pqkmeans`, which is the dependency of `compress-fasttext`. 
So maybe it would make sense to contact the maintainers of `lshash3`. 
Here is their PyPI page https://pypi.org/project/lshash3, but I couldn't find their github. 
Judging from the PyPI page, the maintainer is https://gitlab.com/hobs.

**Comment by HossamAmer12** [comment]
@avidale Do you have a way/patch to get around this error? 

Hobs does not seem easily reachable via social media. I tried.

**Comment by avidale** [comment]
I can probably drop pqkmeans as a dependency, and re-implement their compression algorithm within the compress-fasttext codebase. But it will take more than a moment.

**Comment by HossamAmer12** [comment]
Thanks, @avidale .. Yes, please keep me posted. Btw, are you able to have the correct env on your computer? or you see the same error?

Can you please help me with my questions on either the other issues or the email I sent to you?

**Comment by HossamAmer12** [comment]
@avidale Can we use Faiss PQ instead? If yes, do you have any idea what could be changed?

**Comment by HossamAmer12** [comment]
Just want to say that the [answer ](https://stackoverflow.com/questions/77258294/compressfasttext-pqkmeans-does-not-install)in this SO link solves this pqkmeans issue.

**Comment by avidale** [comment]
@HossamAmer12 
I have just updated `compress-fasttext` to the version `0.1.4` that doesn't require `pqkmeans` as a dependency, and instead copypastes the quantizer from it. 
This version should no longer have the installation problems; please check it out!

**Comment by HossamAmer12** [comment]
> @HossamAmer12 I have just updated `compress-fasttext` to the version `0.1.4` that doesn't require `pqkmeans` as a dependency, and instead copypastes the quantizer from it. This version should no longer have the installation problems; please check it out!

@avidale That's great. Thanks @avidale - I will have a look :))
