### ISSUE TITLE
Using CompressText Source to compress models

### ISSUE THREAD

**Issue by HossamAmer12** [avidale/compress-fasttext#20]
I want to use the compress text source code to compress models without pip install.

Here's my code:

```
org_model_path = "cc.en.300.bin"
ft = load_facebook_model(org_model_path).wv
ft_fp16 = make_new_fasttext_model(ft, ft.vectors.astype(np.float16), ft.vectors_ngrams.astype(np.float16))

```

I see this error 

> TypeError: __init__() missing 1 required positional argument: 'compatible_hash'

It's due to this creation in compress.py

 ```
 new_ft = cls(
        vector_size=ft.vector_size,
        min_n=ft.min_n,
        max_n=ft.max_n,
        bucket=new_vectors_ngrams.shape[0],
    )
```

Any clue? 

I tried to add a true/false compatible_hash, but I got bumped with another error
> AttributeError: 'CompressedFastTextKeyedVectors' object has no attribute 'index_to_key'

**Comment by avidale** [comment]
> I want to use the compress text source code to compress models without pip install.

I am supporting only the `compress-fasttext` package which should normally be installed with pip. 
With this package, the recommended way to compress a model is the following (it is provided in the repository readme):
```
from gensim.models.fasttext import load_facebook_model
import compress_fasttext
big_model = load_facebook_model('path-to-original-model').wv
small_model = compress_fasttext.prune_ft_freq(big_model, pq=True)
small_model.save('path-to-new-model')
```
