### ISSUE TITLE
AssertionError when trying to compress facebook model

### ISSUE THREAD

**Issue by jpatel624** [avidale/compress-fasttext#25]
fasttext 0.9.2
compress-fasttext 0.1.4
gensim-4.3.2
Ubuntu 22.04
numpy 1.23.5  (is this the issue?)

--------------------
Code:
import compress_fasttext
from gensim.models.fasttext import load_facebook_model

gensim_model = load_facebook_model('fasttext-best-4-2-24.bin').wv
small_model = compress_fasttext.prune_ft_freq(gensim_model, pq=True)

---------------------------------------------------------------------------
Error:
AssertionError                            Traceback (most recent call last)
Cell In[30], line 2
      1 gensim_model = load_facebook_model('fasttext-best-4-2-24.bin').wv
----> 2 small_model = compress_fasttext.prune_ft_freq(gensim_model, pq=True)

File ~/git/SIEGE/env/lib/python3.10/site-packages/compress_fasttext/compress.py:231, in prune_ft_freq(ft, new_vocab_size, new_ngrams_size, fp16, pq, qdim, centroids, prune_by_norm, norm_power)
    229 top_voc, top_vec = prune_vocab(ft, new_vocab_size=new_vocab_size)
    230 if pq and len(top_vec) > 0:
--> 231     top_vec = quantize(top_vec, qdim=qdim, centroids=centroids)
    232 elif fp16:
    233     top_vec = top_vec.astype(np.float16)

File ~/git/SIEGE/env/lib/python3.10/site-packages/compress_fasttext/quantization.py:23, in quantize(matrix, qdim, centroids, sample, iterations, verbose)
     20     indexes = np.random.randint(vectors, size=sample)
     21     selection = matrix[indexes]
---> 23 encoder.fit(selection)
     24 indexes = encoder.transform(matrix).astype(PQ.index_type(centroids))
     25 codes = encoder.codewords

File ~/git/SIEGE/env/lib/python3.10/site-packages/compress_fasttext/pq_encoder_light.py:68, in PQEncoder.fit(self, x_train)
     66 assert x_train.ndim == 2
     67 N, D = x_train.shape
---> 68 assert self.Ks < N, "the number of training vector should be more than Ks"
     69 assert D % self.M == 0, "input dimension must be dividable by M"
     70 self.Ds = int(D / self.M)

AssertionError: the number of training vector should be more than Ks

**Comment by avidale** [comment]
@jpatel624 could you please point me to the model file for `fasttext-best-4-2-24.bin`, so that I could reproduce the error?
Or at least describe the parameters of this model, so that I could try to reproduce the error with a similar one.

**Comment by jpatel624** [comment]
Sharing the model might be an issue, but I can share the params.  What do you need and wow do I get them?
BTW I built a gensim fasttext model with my data and I got the identical error.  
The train() output is (344294, 1067260)
(model.corpus_count, model.corpus_total_words) = (1016, 39993). 
vector_size = 100
Hope that gives you some idea.

**Comment by avidale** [comment]
`vector_size = 100`, but how many words and character ngrams are in your model?
In other words, what are `gensim_model.vectors.shape` and `gensim_model.vectors_ngrams.shape`?
The error that you are reporting may indicate that the number of vectors is smaller than the number of centroids into which you want to quantize them, which is indeed an invalid case (and probably the model is already extremely small, so it probably doesn't need any more compression).

**Comment by jpatel624** [comment]
You're right.  The issue is that my vocabulary is too small (model.wv.key_to_index < 256 the default Ks (centroids?)).  However the model is still ~800MB - too big for my use case.  I'll have no problem making the vocabulary bigger and the problem should go away.  I'll close the issue for now.  Thanks for your help.

**Comment by avidale** [comment]
@jpatel624 
If your word vocabulary is so small, but the model is still 800 Mb, this is probably because you are still using a large table for hashed subword embeddings (its default size, if I remember correctly, is 2 million rows). 

Thus, if you can afford this, I suggest that you train a new fasttext model with a radically smaller ngrams embedding table; if the size of this model suits you, there might be no need for compressing it anymore.

Moreover, if your vocabulary is small and fixed (with less than 256 words, it is not a natural language, I guess?), then maybe you don’t need fasttext at all, and a word2vec model (i.e. just a single embedding table for words, without any subwords) would suit you well enough? The idea of fasttext is to support a very long tail (possible infinite) of increasingly rare words (e.g. typos, neologisms, all kinds of proper names, foreign words, etc), by composing unknown (or barely known) words from their character ngrams (which, for a bounded n, are a finite set). If your data doesn’t have such properties (i.e. if the set of all words you expect to encounter is finite and small, and each word is well represented in the training data), then fasttext may be not what you need.

**Comment by jpatel624** [comment]
As I had indicated I now have access to more data and with a much bigger vocabulary I am able to compress my gensim fasttext model.  It seems to work except that get_sentence_vector() always returns a NaN vector.  This works fine on the non-compressed model.
The error I get is: .../env/lib/python3.10/site-packages/gensim/models/fasttext.py:1128: RuntimeWarning: invalid value encountered in divide:  return word_vec / np.linalg.norm(word_vec)

To summarize:

1. I train a gensim fasttext model:
model1 = FastText(vector_size=100)
corpus_file = datapath('/tmp/ds')
model1.build_vocab(corpus_file=corpus_file)
model1.train(
    corpus_file=corpus_file, epochs=20,
    total_examples=model1.corpus_count, total_words=model1.corpus_total_words,
)

2. I compress and save the compressed model:
small_model = compress_fasttext.prune_ft_freq(model1.wv, pq=True)

3. Try to get a sentence vector
um_vector1 = model1.wv.get_sentence_vector("a test sentence")     # generates a proper (100,) vector
vector1 = small_model.get_sentence_vector("a test sentence")     # generates a (100,) vector populated with NaN
.../env/lib/python3.10/site-packages/gensim/models/fasttext.py:1128: RuntimeWarning: invalid value encountered in divide:  return word_vec / np.linalg.norm(word_vec)
vector = small_model["a test sentence"]    # generates a proper (100,) vector

**Comment by xiaofeng-ling** [comment]
> As I had indicated I now have access to more data and with a much bigger vocabulary I am able to compress my gensim fasttext model. It seems to work except that get_sentence_vector() always returns a NaN vector. This works fine on the non-compressed model. The error I get is: .../env/lib/python3.10/site-packages/gensim/models/fasttext.py:1128: RuntimeWarning: invalid value encountered in divide: return word_vec / np.linalg.norm(word_vec)
> 
> To summarize:
> 
> 1. I train a gensim fasttext model:
>    model1 = FastText(vector_size=100)
>    corpus_file = datapath('/tmp/ds')
>    model1.build_vocab(corpus_file=corpus_file)
>    model1.train(
>    corpus_file=corpus_file, epochs=20,
>    total_examples=model1.corpus_count, total_words=model1.corpus_total_words,
>    )
> 2. I compress and save the compressed model:
>    small_model = compress_fasttext.prune_ft_freq(model1.wv, pq=True)
> 3. Try to get a sentence vector
>    um_vector1 = model1.wv.get_sentence_vector("a test sentence")     # generates a proper (100,) vector
>    vector1 = small_model.get_sentence_vector("a test sentence")     # generates a (100,) vector populated with NaN
>    .../env/lib/python3.10/site-packages/gensim/models/fasttext.py:1128: RuntimeWarning: invalid value encountered in divide:  return word_vec / np.linalg.norm(word_vec)
>    vector = small_model["a test sentence"]    # generates a proper (100,) vector

I have the same problem. After checking the code, it seems that when obtaining the ngram vector, all vectors were obtained as 0, and then normalized to Nan. I am currently using **compress_fasttext.feature_extraction.FastTextTransformer**，But the generated vector is different from **get_sentence_vector** and the similarity calculated by **cosine_similarities** varies greatly
